<<<<<<< HEAD
name: Deploy Firebase Hosting (sitio estático)
=======
name: Deploy to Firebase
>>>>>>> develop

on:
  push:
    branches:
      - main

jobs:
<<<<<<< HEAD
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
=======
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
>>>>>>> develop
        uses: actions/setup-node@v4
        with:
          node-version: '18'

<<<<<<< HEAD
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
=======
      - name: Install dependencies
        run: npm install

      - name: Deploy to Firebase
        run: npm run build && npx firebase deploy --only hosting
>>>>>>> develop
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
